// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package gtfsdb

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.clearAgenciesStmt, err = db.PrepareContext(ctx, clearAgencies); err != nil {
		return nil, fmt.Errorf("error preparing query ClearAgencies: %w", err)
	}
	if q.clearBlockTripEntriesStmt, err = db.PrepareContext(ctx, clearBlockTripEntries); err != nil {
		return nil, fmt.Errorf("error preparing query ClearBlockTripEntries: %w", err)
	}
	if q.clearBlockTripIndicesStmt, err = db.PrepareContext(ctx, clearBlockTripIndices); err != nil {
		return nil, fmt.Errorf("error preparing query ClearBlockTripIndices: %w", err)
	}
	if q.clearCalendarStmt, err = db.PrepareContext(ctx, clearCalendar); err != nil {
		return nil, fmt.Errorf("error preparing query ClearCalendar: %w", err)
	}
	if q.clearRoutesStmt, err = db.PrepareContext(ctx, clearRoutes); err != nil {
		return nil, fmt.Errorf("error preparing query ClearRoutes: %w", err)
	}
	if q.clearShapesStmt, err = db.PrepareContext(ctx, clearShapes); err != nil {
		return nil, fmt.Errorf("error preparing query ClearShapes: %w", err)
	}
	if q.clearStopTimesStmt, err = db.PrepareContext(ctx, clearStopTimes); err != nil {
		return nil, fmt.Errorf("error preparing query ClearStopTimes: %w", err)
	}
	if q.clearStopsStmt, err = db.PrepareContext(ctx, clearStops); err != nil {
		return nil, fmt.Errorf("error preparing query ClearStops: %w", err)
	}
	if q.clearTripsStmt, err = db.PrepareContext(ctx, clearTrips); err != nil {
		return nil, fmt.Errorf("error preparing query ClearTrips: %w", err)
	}
	if q.createAgencyStmt, err = db.PrepareContext(ctx, createAgency); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAgency: %w", err)
	}
	if q.createBlockTripEntryStmt, err = db.PrepareContext(ctx, createBlockTripEntry); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBlockTripEntry: %w", err)
	}
	if q.createBlockTripIndexStmt, err = db.PrepareContext(ctx, createBlockTripIndex); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBlockTripIndex: %w", err)
	}
	if q.createCalendarStmt, err = db.PrepareContext(ctx, createCalendar); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCalendar: %w", err)
	}
	if q.createCalendarDateStmt, err = db.PrepareContext(ctx, createCalendarDate); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCalendarDate: %w", err)
	}
	if q.createRouteStmt, err = db.PrepareContext(ctx, createRoute); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRoute: %w", err)
	}
	if q.createShapeStmt, err = db.PrepareContext(ctx, createShape); err != nil {
		return nil, fmt.Errorf("error preparing query CreateShape: %w", err)
	}
	if q.createStopStmt, err = db.PrepareContext(ctx, createStop); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStop: %w", err)
	}
	if q.createStopTimeStmt, err = db.PrepareContext(ctx, createStopTime); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStopTime: %w", err)
	}
	if q.createTripStmt, err = db.PrepareContext(ctx, createTrip); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTrip: %w", err)
	}
	if q.getActiveServiceIDsForDateStmt, err = db.PrepareContext(ctx, getActiveServiceIDsForDate); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveServiceIDsForDate: %w", err)
	}
	if q.getActiveStopsStmt, err = db.PrepareContext(ctx, getActiveStops); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveStops: %w", err)
	}
	if q.getActiveTripForRouteAtTimeStmt, err = db.PrepareContext(ctx, getActiveTripForRouteAtTime); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveTripForRouteAtTime: %w", err)
	}
	if q.getActiveTripInBlockAtTimeStmt, err = db.PrepareContext(ctx, getActiveTripInBlockAtTime); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveTripInBlockAtTime: %w", err)
	}
	if q.getAgenciesForStopsStmt, err = db.PrepareContext(ctx, getAgenciesForStops); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgenciesForStops: %w", err)
	}
	if q.getAgencyStmt, err = db.PrepareContext(ctx, getAgency); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgency: %w", err)
	}
	if q.getAgencyForStopStmt, err = db.PrepareContext(ctx, getAgencyForStop); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgencyForStop: %w", err)
	}
	if q.getAllShapesStmt, err = db.PrepareContext(ctx, getAllShapes); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllShapes: %w", err)
	}
	if q.getAllTripsForRouteStmt, err = db.PrepareContext(ctx, getAllTripsForRoute); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllTripsForRoute: %w", err)
	}
	if q.getArrivalsAndDeparturesForStopStmt, err = db.PrepareContext(ctx, getArrivalsAndDeparturesForStop); err != nil {
		return nil, fmt.Errorf("error preparing query GetArrivalsAndDeparturesForStop: %w", err)
	}
	if q.getBlockDetailsStmt, err = db.PrepareContext(ctx, getBlockDetails); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlockDetails: %w", err)
	}
	if q.getBlockIDByTripIDStmt, err = db.PrepareContext(ctx, getBlockIDByTripID); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlockIDByTripID: %w", err)
	}
	if q.getBlockTripIndexIDsForBlocksStmt, err = db.PrepareContext(ctx, getBlockTripIndexIDsForBlocks); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlockTripIndexIDsForBlocks: %w", err)
	}
	if q.getBlockTripIndexIDsForRouteStmt, err = db.PrepareContext(ctx, getBlockTripIndexIDsForRoute); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlockTripIndexIDsForRoute: %w", err)
	}
	if q.getBlocksForBlockTripIndexIDsStmt, err = db.PrepareContext(ctx, getBlocksForBlockTripIndexIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlocksForBlockTripIndexIDs: %w", err)
	}
	if q.getCalendarByServiceIDStmt, err = db.PrepareContext(ctx, getCalendarByServiceID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCalendarByServiceID: %w", err)
	}
	if q.getCalendarDateExceptionsForServiceIDStmt, err = db.PrepareContext(ctx, getCalendarDateExceptionsForServiceID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCalendarDateExceptionsForServiceID: %w", err)
	}
	if q.getImportMetadataStmt, err = db.PrepareContext(ctx, getImportMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query GetImportMetadata: %w", err)
	}
	if q.getNextStopInTripStmt, err = db.PrepareContext(ctx, getNextStopInTrip); err != nil {
		return nil, fmt.Errorf("error preparing query GetNextStopInTrip: %w", err)
	}
	if q.getOrderedStopIDsForTripStmt, err = db.PrepareContext(ctx, getOrderedStopIDsForTrip); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderedStopIDsForTrip: %w", err)
	}
	if q.getRouteStmt, err = db.PrepareContext(ctx, getRoute); err != nil {
		return nil, fmt.Errorf("error preparing query GetRoute: %w", err)
	}
	if q.getRouteIDsForAgencyStmt, err = db.PrepareContext(ctx, getRouteIDsForAgency); err != nil {
		return nil, fmt.Errorf("error preparing query GetRouteIDsForAgency: %w", err)
	}
	if q.getRouteIDsForStopStmt, err = db.PrepareContext(ctx, getRouteIDsForStop); err != nil {
		return nil, fmt.Errorf("error preparing query GetRouteIDsForStop: %w", err)
	}
	if q.getRouteIDsForStopsStmt, err = db.PrepareContext(ctx, getRouteIDsForStops); err != nil {
		return nil, fmt.Errorf("error preparing query GetRouteIDsForStops: %w", err)
	}
	if q.getRoutesByIDsStmt, err = db.PrepareContext(ctx, getRoutesByIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetRoutesByIDs: %w", err)
	}
	if q.getRoutesForStopStmt, err = db.PrepareContext(ctx, getRoutesForStop); err != nil {
		return nil, fmt.Errorf("error preparing query GetRoutesForStop: %w", err)
	}
	if q.getRoutesForStopsStmt, err = db.PrepareContext(ctx, getRoutesForStops); err != nil {
		return nil, fmt.Errorf("error preparing query GetRoutesForStops: %w", err)
	}
	if q.getRoutesInBlockTripIndicesStmt, err = db.PrepareContext(ctx, getRoutesInBlockTripIndices); err != nil {
		return nil, fmt.Errorf("error preparing query GetRoutesInBlockTripIndices: %w", err)
	}
	if q.getScheduleForStopStmt, err = db.PrepareContext(ctx, getScheduleForStop); err != nil {
		return nil, fmt.Errorf("error preparing query GetScheduleForStop: %w", err)
	}
	if q.getScheduleForStopOnDateStmt, err = db.PrepareContext(ctx, getScheduleForStopOnDate); err != nil {
		return nil, fmt.Errorf("error preparing query GetScheduleForStopOnDate: %w", err)
	}
	if q.getShapeByIDStmt, err = db.PrepareContext(ctx, getShapeByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetShapeByID: %w", err)
	}
	if q.getShapePointWindowStmt, err = db.PrepareContext(ctx, getShapePointWindow); err != nil {
		return nil, fmt.Errorf("error preparing query GetShapePointWindow: %w", err)
	}
	if q.getShapePointsByIDsStmt, err = db.PrepareContext(ctx, getShapePointsByIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetShapePointsByIDs: %w", err)
	}
	if q.getShapePointsByTripIDStmt, err = db.PrepareContext(ctx, getShapePointsByTripID); err != nil {
		return nil, fmt.Errorf("error preparing query GetShapePointsByTripID: %w", err)
	}
	if q.getShapePointsForTripStmt, err = db.PrepareContext(ctx, getShapePointsForTrip); err != nil {
		return nil, fmt.Errorf("error preparing query GetShapePointsForTrip: %w", err)
	}
	if q.getShapePointsWithDistanceStmt, err = db.PrepareContext(ctx, getShapePointsWithDistance); err != nil {
		return nil, fmt.Errorf("error preparing query GetShapePointsWithDistance: %w", err)
	}
	if q.getShapesGroupedByTripHeadSignStmt, err = db.PrepareContext(ctx, getShapesGroupedByTripHeadSign); err != nil {
		return nil, fmt.Errorf("error preparing query GetShapesGroupedByTripHeadSign: %w", err)
	}
	if q.getStopStmt, err = db.PrepareContext(ctx, getStop); err != nil {
		return nil, fmt.Errorf("error preparing query GetStop: %w", err)
	}
	if q.getStopForAgencyStmt, err = db.PrepareContext(ctx, getStopForAgency); err != nil {
		return nil, fmt.Errorf("error preparing query GetStopForAgency: %w", err)
	}
	if q.getStopIDsForAgencyStmt, err = db.PrepareContext(ctx, getStopIDsForAgency); err != nil {
		return nil, fmt.Errorf("error preparing query GetStopIDsForAgency: %w", err)
	}
	if q.getStopIDsForRouteStmt, err = db.PrepareContext(ctx, getStopIDsForRoute); err != nil {
		return nil, fmt.Errorf("error preparing query GetStopIDsForRoute: %w", err)
	}
	if q.getStopIDsForTripStmt, err = db.PrepareContext(ctx, getStopIDsForTrip); err != nil {
		return nil, fmt.Errorf("error preparing query GetStopIDsForTrip: %w", err)
	}
	if q.getStopTimesByStopIDsStmt, err = db.PrepareContext(ctx, getStopTimesByStopIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetStopTimesByStopIDs: %w", err)
	}
	if q.getStopTimesForStopInWindowStmt, err = db.PrepareContext(ctx, getStopTimesForStopInWindow); err != nil {
		return nil, fmt.Errorf("error preparing query GetStopTimesForStopInWindow: %w", err)
	}
	if q.getStopTimesForTripStmt, err = db.PrepareContext(ctx, getStopTimesForTrip); err != nil {
		return nil, fmt.Errorf("error preparing query GetStopTimesForTrip: %w", err)
	}
	if q.getStopsByIDsStmt, err = db.PrepareContext(ctx, getStopsByIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetStopsByIDs: %w", err)
	}
	if q.getStopsForRouteStmt, err = db.PrepareContext(ctx, getStopsForRoute); err != nil {
		return nil, fmt.Errorf("error preparing query GetStopsForRoute: %w", err)
	}
	if q.getStopsWithActiveServiceOnDateStmt, err = db.PrepareContext(ctx, getStopsWithActiveServiceOnDate); err != nil {
		return nil, fmt.Errorf("error preparing query GetStopsWithActiveServiceOnDate: %w", err)
	}
	if q.getStopsWithShapeContextStmt, err = db.PrepareContext(ctx, getStopsWithShapeContext); err != nil {
		return nil, fmt.Errorf("error preparing query GetStopsWithShapeContext: %w", err)
	}
	if q.getStopsWithShapeContextByIDsStmt, err = db.PrepareContext(ctx, getStopsWithShapeContextByIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetStopsWithShapeContextByIDs: %w", err)
	}
	if q.getStopsWithTripContextStmt, err = db.PrepareContext(ctx, getStopsWithTripContext); err != nil {
		return nil, fmt.Errorf("error preparing query GetStopsWithTripContext: %w", err)
	}
	if q.getTripStmt, err = db.PrepareContext(ctx, getTrip); err != nil {
		return nil, fmt.Errorf("error preparing query GetTrip: %w", err)
	}
	if q.getTripsByBlockIDStmt, err = db.PrepareContext(ctx, getTripsByBlockID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTripsByBlockID: %w", err)
	}
	if q.getTripsByBlockIDOrderedStmt, err = db.PrepareContext(ctx, getTripsByBlockIDOrdered); err != nil {
		return nil, fmt.Errorf("error preparing query GetTripsByBlockIDOrdered: %w", err)
	}
	if q.getTripsByBlockTripIndexIDsStmt, err = db.PrepareContext(ctx, getTripsByBlockTripIndexIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetTripsByBlockTripIndexIDs: %w", err)
	}
	if q.getTripsByIDsStmt, err = db.PrepareContext(ctx, getTripsByIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetTripsByIDs: %w", err)
	}
	if q.getTripsByRouteStmt, err = db.PrepareContext(ctx, getTripsByRoute); err != nil {
		return nil, fmt.Errorf("error preparing query GetTripsByRoute: %w", err)
	}
	if q.getTripsByServiceIDStmt, err = db.PrepareContext(ctx, getTripsByServiceID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTripsByServiceID: %w", err)
	}
	if q.getTripsForRouteInActiveServiceIDsStmt, err = db.PrepareContext(ctx, getTripsForRouteInActiveServiceIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetTripsForRouteInActiveServiceIDs: %w", err)
	}
	if q.getTripsInBlockStmt, err = db.PrepareContext(ctx, getTripsInBlock); err != nil {
		return nil, fmt.Errorf("error preparing query GetTripsInBlock: %w", err)
	}
	if q.listAgenciesStmt, err = db.PrepareContext(ctx, listAgencies); err != nil {
		return nil, fmt.Errorf("error preparing query ListAgencies: %w", err)
	}
	if q.listRoutesStmt, err = db.PrepareContext(ctx, listRoutes); err != nil {
		return nil, fmt.Errorf("error preparing query ListRoutes: %w", err)
	}
	if q.listStopsStmt, err = db.PrepareContext(ctx, listStops); err != nil {
		return nil, fmt.Errorf("error preparing query ListStops: %w", err)
	}
	if q.listTripsStmt, err = db.PrepareContext(ctx, listTrips); err != nil {
		return nil, fmt.Errorf("error preparing query ListTrips: %w", err)
	}
	if q.updateStopDirectionStmt, err = db.PrepareContext(ctx, updateStopDirection); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateStopDirection: %w", err)
	}
	if q.upsertImportMetadataStmt, err = db.PrepareContext(ctx, upsertImportMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertImportMetadata: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.clearAgenciesStmt != nil {
		if cerr := q.clearAgenciesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearAgenciesStmt: %w", cerr)
		}
	}
	if q.clearBlockTripEntriesStmt != nil {
		if cerr := q.clearBlockTripEntriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearBlockTripEntriesStmt: %w", cerr)
		}
	}
	if q.clearBlockTripIndicesStmt != nil {
		if cerr := q.clearBlockTripIndicesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearBlockTripIndicesStmt: %w", cerr)
		}
	}
	if q.clearCalendarStmt != nil {
		if cerr := q.clearCalendarStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearCalendarStmt: %w", cerr)
		}
	}
	if q.clearRoutesStmt != nil {
		if cerr := q.clearRoutesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearRoutesStmt: %w", cerr)
		}
	}
	if q.clearShapesStmt != nil {
		if cerr := q.clearShapesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearShapesStmt: %w", cerr)
		}
	}
	if q.clearStopTimesStmt != nil {
		if cerr := q.clearStopTimesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearStopTimesStmt: %w", cerr)
		}
	}
	if q.clearStopsStmt != nil {
		if cerr := q.clearStopsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearStopsStmt: %w", cerr)
		}
	}
	if q.clearTripsStmt != nil {
		if cerr := q.clearTripsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearTripsStmt: %w", cerr)
		}
	}
	if q.createAgencyStmt != nil {
		if cerr := q.createAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAgencyStmt: %w", cerr)
		}
	}
	if q.createBlockTripEntryStmt != nil {
		if cerr := q.createBlockTripEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBlockTripEntryStmt: %w", cerr)
		}
	}
	if q.createBlockTripIndexStmt != nil {
		if cerr := q.createBlockTripIndexStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBlockTripIndexStmt: %w", cerr)
		}
	}
	if q.createCalendarStmt != nil {
		if cerr := q.createCalendarStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCalendarStmt: %w", cerr)
		}
	}
	if q.createCalendarDateStmt != nil {
		if cerr := q.createCalendarDateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCalendarDateStmt: %w", cerr)
		}
	}
	if q.createRouteStmt != nil {
		if cerr := q.createRouteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRouteStmt: %w", cerr)
		}
	}
	if q.createShapeStmt != nil {
		if cerr := q.createShapeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createShapeStmt: %w", cerr)
		}
	}
	if q.createStopStmt != nil {
		if cerr := q.createStopStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStopStmt: %w", cerr)
		}
	}
	if q.createStopTimeStmt != nil {
		if cerr := q.createStopTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStopTimeStmt: %w", cerr)
		}
	}
	if q.createTripStmt != nil {
		if cerr := q.createTripStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTripStmt: %w", cerr)
		}
	}
	if q.getActiveServiceIDsForDateStmt != nil {
		if cerr := q.getActiveServiceIDsForDateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveServiceIDsForDateStmt: %w", cerr)
		}
	}
	if q.getActiveStopsStmt != nil {
		if cerr := q.getActiveStopsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveStopsStmt: %w", cerr)
		}
	}
	if q.getActiveTripForRouteAtTimeStmt != nil {
		if cerr := q.getActiveTripForRouteAtTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveTripForRouteAtTimeStmt: %w", cerr)
		}
	}
	if q.getActiveTripInBlockAtTimeStmt != nil {
		if cerr := q.getActiveTripInBlockAtTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveTripInBlockAtTimeStmt: %w", cerr)
		}
	}
	if q.getAgenciesForStopsStmt != nil {
		if cerr := q.getAgenciesForStopsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgenciesForStopsStmt: %w", cerr)
		}
	}
	if q.getAgencyStmt != nil {
		if cerr := q.getAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgencyStmt: %w", cerr)
		}
	}
	if q.getAgencyForStopStmt != nil {
		if cerr := q.getAgencyForStopStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgencyForStopStmt: %w", cerr)
		}
	}
	if q.getAllShapesStmt != nil {
		if cerr := q.getAllShapesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllShapesStmt: %w", cerr)
		}
	}
	if q.getAllTripsForRouteStmt != nil {
		if cerr := q.getAllTripsForRouteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllTripsForRouteStmt: %w", cerr)
		}
	}
	if q.getArrivalsAndDeparturesForStopStmt != nil {
		if cerr := q.getArrivalsAndDeparturesForStopStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getArrivalsAndDeparturesForStopStmt: %w", cerr)
		}
	}
	if q.getBlockDetailsStmt != nil {
		if cerr := q.getBlockDetailsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlockDetailsStmt: %w", cerr)
		}
	}
	if q.getBlockIDByTripIDStmt != nil {
		if cerr := q.getBlockIDByTripIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlockIDByTripIDStmt: %w", cerr)
		}
	}
	if q.getBlockTripIndexIDsForBlocksStmt != nil {
		if cerr := q.getBlockTripIndexIDsForBlocksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlockTripIndexIDsForBlocksStmt: %w", cerr)
		}
	}
	if q.getBlockTripIndexIDsForRouteStmt != nil {
		if cerr := q.getBlockTripIndexIDsForRouteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlockTripIndexIDsForRouteStmt: %w", cerr)
		}
	}
	if q.getBlocksForBlockTripIndexIDsStmt != nil {
		if cerr := q.getBlocksForBlockTripIndexIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlocksForBlockTripIndexIDsStmt: %w", cerr)
		}
	}
	if q.getCalendarByServiceIDStmt != nil {
		if cerr := q.getCalendarByServiceIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCalendarByServiceIDStmt: %w", cerr)
		}
	}
	if q.getCalendarDateExceptionsForServiceIDStmt != nil {
		if cerr := q.getCalendarDateExceptionsForServiceIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCalendarDateExceptionsForServiceIDStmt: %w", cerr)
		}
	}
	if q.getImportMetadataStmt != nil {
		if cerr := q.getImportMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getImportMetadataStmt: %w", cerr)
		}
	}
	if q.getNextStopInTripStmt != nil {
		if cerr := q.getNextStopInTripStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNextStopInTripStmt: %w", cerr)
		}
	}
	if q.getOrderedStopIDsForTripStmt != nil {
		if cerr := q.getOrderedStopIDsForTripStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderedStopIDsForTripStmt: %w", cerr)
		}
	}
	if q.getRouteStmt != nil {
		if cerr := q.getRouteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRouteStmt: %w", cerr)
		}
	}
	if q.getRouteIDsForAgencyStmt != nil {
		if cerr := q.getRouteIDsForAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRouteIDsForAgencyStmt: %w", cerr)
		}
	}
	if q.getRouteIDsForStopStmt != nil {
		if cerr := q.getRouteIDsForStopStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRouteIDsForStopStmt: %w", cerr)
		}
	}
	if q.getRouteIDsForStopsStmt != nil {
		if cerr := q.getRouteIDsForStopsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRouteIDsForStopsStmt: %w", cerr)
		}
	}
	if q.getRoutesByIDsStmt != nil {
		if cerr := q.getRoutesByIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRoutesByIDsStmt: %w", cerr)
		}
	}
	if q.getRoutesForStopStmt != nil {
		if cerr := q.getRoutesForStopStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRoutesForStopStmt: %w", cerr)
		}
	}
	if q.getRoutesForStopsStmt != nil {
		if cerr := q.getRoutesForStopsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRoutesForStopsStmt: %w", cerr)
		}
	}
	if q.getRoutesInBlockTripIndicesStmt != nil {
		if cerr := q.getRoutesInBlockTripIndicesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRoutesInBlockTripIndicesStmt: %w", cerr)
		}
	}
	if q.getScheduleForStopStmt != nil {
		if cerr := q.getScheduleForStopStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getScheduleForStopStmt: %w", cerr)
		}
	}
	if q.getScheduleForStopOnDateStmt != nil {
		if cerr := q.getScheduleForStopOnDateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getScheduleForStopOnDateStmt: %w", cerr)
		}
	}
	if q.getShapeByIDStmt != nil {
		if cerr := q.getShapeByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getShapeByIDStmt: %w", cerr)
		}
	}
	if q.getShapePointWindowStmt != nil {
		if cerr := q.getShapePointWindowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getShapePointWindowStmt: %w", cerr)
		}
	}
	if q.getShapePointsByIDsStmt != nil {
		if cerr := q.getShapePointsByIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getShapePointsByIDsStmt: %w", cerr)
		}
	}
	if q.getShapePointsByTripIDStmt != nil {
		if cerr := q.getShapePointsByTripIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getShapePointsByTripIDStmt: %w", cerr)
		}
	}
	if q.getShapePointsForTripStmt != nil {
		if cerr := q.getShapePointsForTripStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getShapePointsForTripStmt: %w", cerr)
		}
	}
	if q.getShapePointsWithDistanceStmt != nil {
		if cerr := q.getShapePointsWithDistanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getShapePointsWithDistanceStmt: %w", cerr)
		}
	}
	if q.getShapesGroupedByTripHeadSignStmt != nil {
		if cerr := q.getShapesGroupedByTripHeadSignStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getShapesGroupedByTripHeadSignStmt: %w", cerr)
		}
	}
	if q.getStopStmt != nil {
		if cerr := q.getStopStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStopStmt: %w", cerr)
		}
	}
	if q.getStopForAgencyStmt != nil {
		if cerr := q.getStopForAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStopForAgencyStmt: %w", cerr)
		}
	}
	if q.getStopIDsForAgencyStmt != nil {
		if cerr := q.getStopIDsForAgencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStopIDsForAgencyStmt: %w", cerr)
		}
	}
	if q.getStopIDsForRouteStmt != nil {
		if cerr := q.getStopIDsForRouteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStopIDsForRouteStmt: %w", cerr)
		}
	}
	if q.getStopIDsForTripStmt != nil {
		if cerr := q.getStopIDsForTripStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStopIDsForTripStmt: %w", cerr)
		}
	}
	if q.getStopTimesByStopIDsStmt != nil {
		if cerr := q.getStopTimesByStopIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStopTimesByStopIDsStmt: %w", cerr)
		}
	}
	if q.getStopTimesForStopInWindowStmt != nil {
		if cerr := q.getStopTimesForStopInWindowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStopTimesForStopInWindowStmt: %w", cerr)
		}
	}
	if q.getStopTimesForTripStmt != nil {
		if cerr := q.getStopTimesForTripStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStopTimesForTripStmt: %w", cerr)
		}
	}
	if q.getStopsByIDsStmt != nil {
		if cerr := q.getStopsByIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStopsByIDsStmt: %w", cerr)
		}
	}
	if q.getStopsForRouteStmt != nil {
		if cerr := q.getStopsForRouteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStopsForRouteStmt: %w", cerr)
		}
	}
	if q.getStopsWithActiveServiceOnDateStmt != nil {
		if cerr := q.getStopsWithActiveServiceOnDateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStopsWithActiveServiceOnDateStmt: %w", cerr)
		}
	}
	if q.getStopsWithShapeContextStmt != nil {
		if cerr := q.getStopsWithShapeContextStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStopsWithShapeContextStmt: %w", cerr)
		}
	}
	if q.getStopsWithShapeContextByIDsStmt != nil {
		if cerr := q.getStopsWithShapeContextByIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStopsWithShapeContextByIDsStmt: %w", cerr)
		}
	}
	if q.getStopsWithTripContextStmt != nil {
		if cerr := q.getStopsWithTripContextStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStopsWithTripContextStmt: %w", cerr)
		}
	}
	if q.getTripStmt != nil {
		if cerr := q.getTripStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTripStmt: %w", cerr)
		}
	}
	if q.getTripsByBlockIDStmt != nil {
		if cerr := q.getTripsByBlockIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTripsByBlockIDStmt: %w", cerr)
		}
	}
	if q.getTripsByBlockIDOrderedStmt != nil {
		if cerr := q.getTripsByBlockIDOrderedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTripsByBlockIDOrderedStmt: %w", cerr)
		}
	}
	if q.getTripsByBlockTripIndexIDsStmt != nil {
		if cerr := q.getTripsByBlockTripIndexIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTripsByBlockTripIndexIDsStmt: %w", cerr)
		}
	}
	if q.getTripsByIDsStmt != nil {
		if cerr := q.getTripsByIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTripsByIDsStmt: %w", cerr)
		}
	}
	if q.getTripsByRouteStmt != nil {
		if cerr := q.getTripsByRouteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTripsByRouteStmt: %w", cerr)
		}
	}
	if q.getTripsByServiceIDStmt != nil {
		if cerr := q.getTripsByServiceIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTripsByServiceIDStmt: %w", cerr)
		}
	}
	if q.getTripsForRouteInActiveServiceIDsStmt != nil {
		if cerr := q.getTripsForRouteInActiveServiceIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTripsForRouteInActiveServiceIDsStmt: %w", cerr)
		}
	}
	if q.getTripsInBlockStmt != nil {
		if cerr := q.getTripsInBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTripsInBlockStmt: %w", cerr)
		}
	}
	if q.listAgenciesStmt != nil {
		if cerr := q.listAgenciesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAgenciesStmt: %w", cerr)
		}
	}
	if q.listRoutesStmt != nil {
		if cerr := q.listRoutesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRoutesStmt: %w", cerr)
		}
	}
	if q.listStopsStmt != nil {
		if cerr := q.listStopsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStopsStmt: %w", cerr)
		}
	}
	if q.listTripsStmt != nil {
		if cerr := q.listTripsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTripsStmt: %w", cerr)
		}
	}
	if q.updateStopDirectionStmt != nil {
		if cerr := q.updateStopDirectionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStopDirectionStmt: %w", cerr)
		}
	}
	if q.upsertImportMetadataStmt != nil {
		if cerr := q.upsertImportMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertImportMetadataStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                        DBTX
	tx                                        *sql.Tx
	clearAgenciesStmt                         *sql.Stmt
	clearBlockTripEntriesStmt                 *sql.Stmt
	clearBlockTripIndicesStmt                 *sql.Stmt
	clearCalendarStmt                         *sql.Stmt
	clearRoutesStmt                           *sql.Stmt
	clearShapesStmt                           *sql.Stmt
	clearStopTimesStmt                        *sql.Stmt
	clearStopsStmt                            *sql.Stmt
	clearTripsStmt                            *sql.Stmt
	createAgencyStmt                          *sql.Stmt
	createBlockTripEntryStmt                  *sql.Stmt
	createBlockTripIndexStmt                  *sql.Stmt
	createCalendarStmt                        *sql.Stmt
	createCalendarDateStmt                    *sql.Stmt
	createRouteStmt                           *sql.Stmt
	createShapeStmt                           *sql.Stmt
	createStopStmt                            *sql.Stmt
	createStopTimeStmt                        *sql.Stmt
	createTripStmt                            *sql.Stmt
	getActiveServiceIDsForDateStmt            *sql.Stmt
	getActiveStopsStmt                        *sql.Stmt
	getActiveTripForRouteAtTimeStmt           *sql.Stmt
	getActiveTripInBlockAtTimeStmt            *sql.Stmt
	getAgenciesForStopsStmt                   *sql.Stmt
	getAgencyStmt                             *sql.Stmt
	getAgencyForStopStmt                      *sql.Stmt
	getAllShapesStmt                          *sql.Stmt
	getAllTripsForRouteStmt                   *sql.Stmt
	getArrivalsAndDeparturesForStopStmt       *sql.Stmt
	getBlockDetailsStmt                       *sql.Stmt
	getBlockIDByTripIDStmt                    *sql.Stmt
	getBlockTripIndexIDsForBlocksStmt         *sql.Stmt
	getBlockTripIndexIDsForRouteStmt          *sql.Stmt
	getBlocksForBlockTripIndexIDsStmt         *sql.Stmt
	getCalendarByServiceIDStmt                *sql.Stmt
	getCalendarDateExceptionsForServiceIDStmt *sql.Stmt
	getImportMetadataStmt                     *sql.Stmt
	getNextStopInTripStmt                     *sql.Stmt
	getOrderedStopIDsForTripStmt              *sql.Stmt
	getRouteStmt                              *sql.Stmt
	getRouteIDsForAgencyStmt                  *sql.Stmt
	getRouteIDsForStopStmt                    *sql.Stmt
	getRouteIDsForStopsStmt                   *sql.Stmt
	getRoutesByIDsStmt                        *sql.Stmt
	getRoutesForStopStmt                      *sql.Stmt
	getRoutesForStopsStmt                     *sql.Stmt
	getRoutesInBlockTripIndicesStmt           *sql.Stmt
	getScheduleForStopStmt                    *sql.Stmt
	getScheduleForStopOnDateStmt              *sql.Stmt
	getShapeByIDStmt                          *sql.Stmt
	getShapePointWindowStmt                   *sql.Stmt
	getShapePointsByIDsStmt                   *sql.Stmt
	getShapePointsByTripIDStmt                *sql.Stmt
	getShapePointsForTripStmt                 *sql.Stmt
	getShapePointsWithDistanceStmt            *sql.Stmt
	getShapesGroupedByTripHeadSignStmt        *sql.Stmt
	getStopStmt                               *sql.Stmt
	getStopForAgencyStmt                      *sql.Stmt
	getStopIDsForAgencyStmt                   *sql.Stmt
	getStopIDsForRouteStmt                    *sql.Stmt
	getStopIDsForTripStmt                     *sql.Stmt
	getStopTimesByStopIDsStmt                 *sql.Stmt
	getStopTimesForStopInWindowStmt           *sql.Stmt
	getStopTimesForTripStmt                   *sql.Stmt
	getStopsByIDsStmt                         *sql.Stmt
	getStopsForRouteStmt                      *sql.Stmt
	getStopsWithActiveServiceOnDateStmt       *sql.Stmt
	getStopsWithShapeContextStmt              *sql.Stmt
	getStopsWithShapeContextByIDsStmt         *sql.Stmt
	getStopsWithTripContextStmt               *sql.Stmt
	getTripStmt                               *sql.Stmt
	getTripsByBlockIDStmt                     *sql.Stmt
	getTripsByBlockIDOrderedStmt              *sql.Stmt
	getTripsByBlockTripIndexIDsStmt           *sql.Stmt
	getTripsByIDsStmt                         *sql.Stmt
	getTripsByRouteStmt                       *sql.Stmt
	getTripsByServiceIDStmt                   *sql.Stmt
	getTripsForRouteInActiveServiceIDsStmt    *sql.Stmt
	getTripsInBlockStmt                       *sql.Stmt
	listAgenciesStmt                          *sql.Stmt
	listRoutesStmt                            *sql.Stmt
	listStopsStmt                             *sql.Stmt
	listTripsStmt                             *sql.Stmt
	updateStopDirectionStmt                   *sql.Stmt
	upsertImportMetadataStmt                  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                        tx,
		tx:                                        tx,
		clearAgenciesStmt:                         q.clearAgenciesStmt,
		clearBlockTripEntriesStmt:                 q.clearBlockTripEntriesStmt,
		clearBlockTripIndicesStmt:                 q.clearBlockTripIndicesStmt,
		clearCalendarStmt:                         q.clearCalendarStmt,
		clearRoutesStmt:                           q.clearRoutesStmt,
		clearShapesStmt:                           q.clearShapesStmt,
		clearStopTimesStmt:                        q.clearStopTimesStmt,
		clearStopsStmt:                            q.clearStopsStmt,
		clearTripsStmt:                            q.clearTripsStmt,
		createAgencyStmt:                          q.createAgencyStmt,
		createBlockTripEntryStmt:                  q.createBlockTripEntryStmt,
		createBlockTripIndexStmt:                  q.createBlockTripIndexStmt,
		createCalendarStmt:                        q.createCalendarStmt,
		createCalendarDateStmt:                    q.createCalendarDateStmt,
		createRouteStmt:                           q.createRouteStmt,
		createShapeStmt:                           q.createShapeStmt,
		createStopStmt:                            q.createStopStmt,
		createStopTimeStmt:                        q.createStopTimeStmt,
		createTripStmt:                            q.createTripStmt,
		getActiveServiceIDsForDateStmt:            q.getActiveServiceIDsForDateStmt,
		getActiveStopsStmt:                        q.getActiveStopsStmt,
		getActiveTripForRouteAtTimeStmt:           q.getActiveTripForRouteAtTimeStmt,
		getActiveTripInBlockAtTimeStmt:            q.getActiveTripInBlockAtTimeStmt,
		getAgenciesForStopsStmt:                   q.getAgenciesForStopsStmt,
		getAgencyStmt:                             q.getAgencyStmt,
		getAgencyForStopStmt:                      q.getAgencyForStopStmt,
		getAllShapesStmt:                          q.getAllShapesStmt,
		getAllTripsForRouteStmt:                   q.getAllTripsForRouteStmt,
		getArrivalsAndDeparturesForStopStmt:       q.getArrivalsAndDeparturesForStopStmt,
		getBlockDetailsStmt:                       q.getBlockDetailsStmt,
		getBlockIDByTripIDStmt:                    q.getBlockIDByTripIDStmt,
		getBlockTripIndexIDsForBlocksStmt:         q.getBlockTripIndexIDsForBlocksStmt,
		getBlockTripIndexIDsForRouteStmt:          q.getBlockTripIndexIDsForRouteStmt,
		getBlocksForBlockTripIndexIDsStmt:         q.getBlocksForBlockTripIndexIDsStmt,
		getCalendarByServiceIDStmt:                q.getCalendarByServiceIDStmt,
		getCalendarDateExceptionsForServiceIDStmt: q.getCalendarDateExceptionsForServiceIDStmt,
		getImportMetadataStmt:                     q.getImportMetadataStmt,
		getNextStopInTripStmt:                     q.getNextStopInTripStmt,
		getOrderedStopIDsForTripStmt:              q.getOrderedStopIDsForTripStmt,
		getRouteStmt:                              q.getRouteStmt,
		getRouteIDsForAgencyStmt:                  q.getRouteIDsForAgencyStmt,
		getRouteIDsForStopStmt:                    q.getRouteIDsForStopStmt,
		getRouteIDsForStopsStmt:                   q.getRouteIDsForStopsStmt,
		getRoutesByIDsStmt:                        q.getRoutesByIDsStmt,
		getRoutesForStopStmt:                      q.getRoutesForStopStmt,
		getRoutesForStopsStmt:                     q.getRoutesForStopsStmt,
		getRoutesInBlockTripIndicesStmt:           q.getRoutesInBlockTripIndicesStmt,
		getScheduleForStopStmt:                    q.getScheduleForStopStmt,
		getScheduleForStopOnDateStmt:              q.getScheduleForStopOnDateStmt,
		getShapeByIDStmt:                          q.getShapeByIDStmt,
		getShapePointWindowStmt:                   q.getShapePointWindowStmt,
		getShapePointsByIDsStmt:                   q.getShapePointsByIDsStmt,
		getShapePointsByTripIDStmt:                q.getShapePointsByTripIDStmt,
		getShapePointsForTripStmt:                 q.getShapePointsForTripStmt,
		getShapePointsWithDistanceStmt:            q.getShapePointsWithDistanceStmt,
		getShapesGroupedByTripHeadSignStmt:        q.getShapesGroupedByTripHeadSignStmt,
		getStopStmt:                               q.getStopStmt,
		getStopForAgencyStmt:                      q.getStopForAgencyStmt,
		getStopIDsForAgencyStmt:                   q.getStopIDsForAgencyStmt,
		getStopIDsForRouteStmt:                    q.getStopIDsForRouteStmt,
		getStopIDsForTripStmt:                     q.getStopIDsForTripStmt,
		getStopTimesByStopIDsStmt:                 q.getStopTimesByStopIDsStmt,
		getStopTimesForStopInWindowStmt:           q.getStopTimesForStopInWindowStmt,
		getStopTimesForTripStmt:                   q.getStopTimesForTripStmt,
		getStopsByIDsStmt:                         q.getStopsByIDsStmt,
		getStopsForRouteStmt:                      q.getStopsForRouteStmt,
		getStopsWithActiveServiceOnDateStmt:       q.getStopsWithActiveServiceOnDateStmt,
		getStopsWithShapeContextStmt:              q.getStopsWithShapeContextStmt,
		getStopsWithShapeContextByIDsStmt:         q.getStopsWithShapeContextByIDsStmt,
		getStopsWithTripContextStmt:               q.getStopsWithTripContextStmt,
		getTripStmt:                               q.getTripStmt,
		getTripsByBlockIDStmt:                     q.getTripsByBlockIDStmt,
		getTripsByBlockIDOrderedStmt:              q.getTripsByBlockIDOrderedStmt,
		getTripsByBlockTripIndexIDsStmt:           q.getTripsByBlockTripIndexIDsStmt,
		getTripsByIDsStmt:                         q.getTripsByIDsStmt,
		getTripsByRouteStmt:                       q.getTripsByRouteStmt,
		getTripsByServiceIDStmt:                   q.getTripsByServiceIDStmt,
		getTripsForRouteInActiveServiceIDsStmt:    q.getTripsForRouteInActiveServiceIDsStmt,
		getTripsInBlockStmt:                       q.getTripsInBlockStmt,
		listAgenciesStmt:                          q.listAgenciesStmt,
		listRoutesStmt:                            q.listRoutesStmt,
		listStopsStmt:                             q.listStopsStmt,
		listTripsStmt:                             q.listTripsStmt,
		updateStopDirectionStmt:                   q.updateStopDirectionStmt,
		upsertImportMetadataStmt:                  q.upsertImportMetadataStmt,
	}
}
