// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gtfsdb

import (
	"database/sql"
)

type Agency struct {
	ID       string
	Name     string
	Url      string
	Timezone string
	Lang     sql.NullString
	Phone    sql.NullString
	FareUrl  sql.NullString
	Email    sql.NullString
}

type BlockTripEntry struct {
	ID                int64
	BlockTripIndexID  int64
	TripID            string
	BlockID           sql.NullString
	ServiceID         string
	BlockTripSequence int64
}

type BlockTripIndex struct {
	ID              int64
	IndexKey        string
	ServiceIds      string
	StopSequenceKey string
	CreatedAt       int64
}

type Calendar struct {
	ID        string
	Monday    int64
	Tuesday   int64
	Wednesday int64
	Thursday  int64
	Friday    int64
	Saturday  int64
	Sunday    int64
	StartDate string
	EndDate   string
}

type CalendarDate struct {
	ServiceID     string
	Date          string
	ExceptionType int64
}

type ImportMetadatum struct {
	ID         int64
	FileHash   string
	ImportTime int64
	FileSource string
}

type Route struct {
	ID                string
	AgencyID          string
	ShortName         sql.NullString
	LongName          sql.NullString
	Desc              sql.NullString
	Type              int64
	Url               sql.NullString
	Color             sql.NullString
	TextColor         sql.NullString
	ContinuousPickup  sql.NullInt64
	ContinuousDropOff sql.NullInt64
}

type RoutesFt struct {
	ID        string
	AgencyID  string
	ShortName string
	LongName  string
	Desc      string
}

type Shape struct {
	ID                int64
	ShapeID           string
	Lat               float64
	Lon               float64
	ShapePtSequence   int64
	ShapeDistTraveled sql.NullFloat64
}

type Stop struct {
	ID                 string
	Code               sql.NullString
	Name               sql.NullString
	Desc               sql.NullString
	Lat                float64
	Lon                float64
	ZoneID             sql.NullString
	Url                sql.NullString
	LocationType       sql.NullInt64
	Timezone           sql.NullString
	WheelchairBoarding sql.NullInt64
	PlatformCode       sql.NullString
	Direction          sql.NullString
	ParentStation      sql.NullString
}

type StopTime struct {
	TripID            string
	ArrivalTime       int64
	DepartureTime     int64
	StopID            string
	StopSequence      int64
	StopHeadsign      sql.NullString
	PickupType        sql.NullInt64
	DropOffType       sql.NullInt64
	ShapeDistTraveled sql.NullFloat64
	Timepoint         sql.NullInt64
}

type StopsFt struct {
	ID       string
	StopName string
}

type StopsRtreeNode struct {
	Nodeno int64
	Data   interface{}
}

type StopsRtreeParent struct {
	Nodeno     int64
	Parentnode interface{}
}

type StopsRtreeRowid struct {
	Rowid  int64
	Nodeno interface{}
}

type Trip struct {
	ID                   string
	RouteID              string
	ServiceID            string
	TripHeadsign         sql.NullString
	TripShortName        sql.NullString
	DirectionID          sql.NullInt64
	BlockID              sql.NullString
	ShapeID              sql.NullString
	WheelchairAccessible sql.NullInt64
	BikesAllowed         sql.NullInt64
}
